# -*- coding: utf-8 -*-
"""2501132130 Krishna Rochani Question 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ehino7bXoj7NI5Pz3POK8px0U-w2MhvB
"""

#fibonacci series
n = int(input("Enter number of terms: "))
a, b = 0, 1
for i in range(n):
    print(a, end=" ")
    a, b = b, a + b

def geometric_sum(a, r, n):
    """
    a = first term
    r = common ratio
    n = number of terms
    """
    if r == 1:
        return a * n
    else:
        return a * (1 - r**n) / (1 - r)

# Example
a = 2
r = 3
n = 5

result = geometric_sum(a, r, n)
print("Sum of geometric series:", result)

def arithmetic_sum(a, d, n):
    """
    a = first term
    d = common difference
    n = number of terms
    """
    return (n / 2) * (2 * a + (n - 1) * d)

# Example
a = 2
d = 3
n = 5

result = arithmetic_sum(a, d, n)
print("Sum of arithmetic series:", result)

def tower_of_hanoi(n, source, auxiliary, destination):
    """
    n = number of disks
    source = starting rod
    auxiliary = helper rod
    destination = target rod
    """
    if n == 1:
        print(f"Move disk 1 from {source} to {destination}")
        return
    tower_of_hanoi(n - 1, source, destination, auxiliary)
    print(f"Move disk {n} from {source} to {destination}")
    tower_of_hanoi(n - 1, auxiliary, source, destination)


# Example
n = 3
tower_of_hanoi(n, 'A', 'B', 'C')

