# -*- coding: utf-8 -*-
"""2501132130 Krishna Rochani Question 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g3xmLbhd-YEpe1krKzdWPZ2OmzX9qfIA
"""

import pandas as pd
import numpy as np
df = pd.read_csv('Salary_dataset.csv')

df.head()

df.tail()

df.describe()

df.info()

df.isnull().sum()

X = df[['YearsExperience']]
y = df['Salary']

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X, y)

print(f"Intercept: {model.intercept_}")
print(f"Slope: {model.coef_[0]}")
print(f"R-squared: {model.score(X, y)}")

y_pred = model.predict(X)

residuals = y - y_pred
print(pd.Series(residuals).describe())

import matplotlib.pyplot as plt
plt.figure(figsize=(10, 6))
plt.scatter(X, y, alpha=0.7, label='Actual')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.title('Linear Regression: Salary vs Experience')
plt.legend()
plt.show()

plt.plot(X, y_pred, color='red', label='Predicted')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.title('Linear Regression: Salary vs Experience')
plt.show()

