# -*- coding: utf-8 -*-
"""fybtechAiml_2501132130.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oCXltinh7PWzov0rSCnOWAIRAXdvPKdO
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('bodyfat.csv')

df.isnull().sum()



df.describe()

df.shape

df.dtypes

x=df['Age']
y=df['BodyFat']
plt.scatter(x,y)
plt.title("Scatter Diagram")
plt.xlabel("Age")
plt.ylabel("BodyFat")
plt.show()

df['Weight'].isnull().sum()

df['Chest'].isnull().sum()

df['Knee'].isnull().sum()

Experience = [1,2,3,4,5] Salary = [30,35,40,50,55]

df.columns.isnull().sum()

plt.figure(figsize=(8,5))
x=df['Age']
y=df['BodyFat']
sns.histplot([x,y])
plt.title("Histogram")
plt.xlabel("Age")
plt.ylabel("BodyFat")
plt.show()

x=df['Age']
y=df['BodyFat']
sns.piechart([x,y])
plt.title("Pie Chart")
plt.xlabel("Age")
plt.ylabel("BodyFat")
plt.show()

import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

# Data
X = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)
Y = np.array([30,35,40,50,55])

# Create & fit model
model = LinearRegression()
model.fit(X, Y)

# Coefficients
print("Slope (b1) =", model.coef_[0])
print("Intercept (b0) =", model.intercept_)

# Predict salary for experience = 6
print("Prediction for 6 years experience =", model.predict([[6]])[0])
#prediction salary for experience = 7
print("Prediction for 7 years experience =",model.predict([[7]])[0])

