# -*- coding: utf-8 -*-
"""practical 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K7bRDCChLP6fs4CKAKwJ26Evs-FePFG8
"""

import pandas as pd

df=pd.read_csv("/content/heart.csv")

df.head()

# skill 1
# title: understanding basic of data visualization and data analystics
# prn :2501132044
# date : 24/9/2025

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# import the dataset
df=pd.read_csv('heart.csv')
df

df.tail()

#what is the shape of the data
df.shape

# what are the features ? columns
df.columns

df.describe()

df.dtypes

# check the missing values
df.isnull().sum()

df.corr()
#relation

#how many male and how many female
df['sex'].value_counts()

df[df['age'] >=30 ]

df[df['age']>30].shape

# what is the average age and fasting blood sugar
df['age'].mean()

df['age'].median()
#median  age

df['age'].mode()
# mode of age

df['fbs'].mean()

# how many female patients age is above 60
 df[(df['sex']==0) & (df['age']>60)].shape
 #how many male patients age is below 60
 df[(df['sex']==1) & (df['age']<60)].shape

# fbs: (fasting blood sugar > 120 ml/dl )
df[(df['sex']==1) & (df['fbs']==1) & (df['target']==1) & (df['chol']<=210)]

df=df.rename(columns={'sex':'gender'})

df