# -*- coding: utf-8 -*-
"""Python1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bp9tyLyM0dTHq9ugyRhWnkpoe-ya-71f

#### This is my first python code
"""

print('Hello World!')

# Write a program to add two numbers
num1 = 10
num2 = 20
num3 = num1 + num2
print(f'The addition of {num1} and {num2} is {num3}')

# Inbuilt data types
# 1.List
Fruits = ['Banana', 'Mango', 'Stawberry', 'Orange', 'Grapes', 'Apple']
print(Fruits)

# Type of the literal
type(Fruits)

# Indexing
Fruits[0]

Fruits[5]

Fruits[-1]

# Slicing
Fruits_day1 = Fruits[0:3]
Fruits_day1

Fruits

# reversing a list
Fruits[::]

Fruits[::-1]

# 2. Tuple
T_Fruits = ('Banana', 'Mango', 'Stawberry', 'Orange', 'Grapes', 'Apple')
T_Fruits

type(T_Fruits)

One_Fruits = 1
type(One_Fruits)

One_Fruits = 1,
type(One_Fruits)

T_Fruits[4]

T_Fruits_day1 = T_Fruits[0:2]
T_Fruits_day1

Fruits.append('Kiwi')
Fruits

"""### The list is mutable and tuple is immutable"""

set_car = {'maruti', 'hundai', 'mahindra', 'tata', 3.5, 5,5, 5}
set_car

# Control statements

for (i) in range(1,10):
  if(i%2==0):
    print(i)
  else:
    print('The numbers are odd')

# Program to find largest no. of given 3 numbers

def largest_no (num1 , num2):
  if num1 > num2:
    print(f'{num1} is largest')
  else:
    print (f'{num2} is largest')

largest_no(10,20)

from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('/content/drive/MyDrive/Python_AIML')

import Large

Large.largest_no(50,200)

def small_no (num1 , num2):
  if num1 < num2:
    print(f'{num1} is small')
  else:
    print (f'{num2} is small')

small_no (15 , 20)

import Small

Small.small_no(200,100)

import Number_Compare

from Number_Compare import Large,Small

Large.largest_no(400,500)

Number_Compare.Large.largest_no(4,5)

Number_Compare.Small.small_no(4,5)