# -*- coding: utf-8 -*-
"""Python2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vlAbNk4jU0Mqj6mB-oAyZdkA7DyCt8e9

###This is my first python code
"""

print('Hello World!')

#Addition
num1 = float(input("Enter first number for addition:"))
num2 = float(input("Enter second number for addition:"))
sum_result = num1 + num2
print(f'{num1} + {num2} = {sum_result}')

first_name = input("Enter your first name:")
last_name = input("Enter your last name:")

prn = (input("Enter your 10 digit prn:"))
while not (prn.isdigit() and len(prn) == 10):
  print("Invalid PRN!")
  prn = input("Enter 10 digit number")

print("Valid PRN:",prn)
marks = int(input("Enter your marks (0-50):"))
while marks < 0 and marks > 50:
  print("Invalid marks!")
  marks = int(input("Enter your marks (0-50)"))
if marks > 20:
  result = "Pass"
else:
  result = "Fail"

print("Name:", first_name , last_name)
print("PRN:", prn)
print("Marks", marks)
print("Result", result)

#Write a Python Program to Check Prime Number in given range
start = int(input("Enter start of range:"))
end = int(input("Enter end of range:"))
print("Prime numbers in the given range are:")

count = 0

for num in range (start,end + 1):
  if num > 1:
    is_prime = True

    for i in range(2,num):
      if num % i == 0:
        is_prime = False
        break

    if is_prime:
      count = count + 1
print("Total prime numbers in given range:", count)

def function_name(parameters):
    """docstring"""
    return value

def add(a: int, b: int) -> int:
    """Return sum of two integers."""
    return a + b

result = add(3, 5)
print(result)

lambda arguments: expression

square = lambda x: x * x
print(square(4))

