# -*- coding: utf-8 -*-
"""Python3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G0lo0PDQPH7R3o-PoLCS3ONlwaKoXdhc
"""

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Datasets/iris dataset.csv")

from google.colab import drive
drive.mount('/content/drive')

import ukaggleimport kagglehub

# Download latest version
df = kagglehub.dataset_download("uciml/iris")

print("Path to dataset files:", df)

df = pd.read_csv('Iris.csv')

df.info()

df.describe()

"""Importing the matplotlib"""

import matplotlib.pyplot as plt

x = df['5,1']
y = df['3,5']
plt.scatter(x,y)
plt.xlabel("5,1")
plt.ylabel("3,5")
plt.title("Scatter plot of years of 5,1 and 3,5")

df.count

df.group('Species').count()

