# -*- coding: utf-8 -*-
"""Skill_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yKNSSiOqtdkP2TSK_0PJL6Zwn26ov4U1

# Skill 02:- Descriptive Statistics using Python
# Student Study Hours vs Exam Marks
# to analyze how study hours (X) affect exam marks (Y)

# Coefficient of Variation → shows consistency of marks vs study hours.

Moments, Skewness, Kurtosis → show distribution of study hours/marks.

Correlation → checks relationship strength.

Regression → predicts marks from study hours (ML model)
"""

import numpy as np
import pandas as pd
from scipy.stats import skew, kurtosis, moment, pearsonr, spearmanr
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

# -----------------------------
# Application Data (Study Hours vs Exam Marks)
# -----------------------------
study_hours = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
marks = np.array([35, 40, 45, 50, 60, 65, 70, 78, 85, 90])

data = pd.DataFrame({'Study Hours': study_hours, 'Marks': marks})

# -----------------------------
# Coefficient of Variation
# -----------------------------
def coefficient_of_variation(arr):
    return np.std(arr, ddof=1) / np.mean(arr)

cv_hours = coefficient_of_variation(data['Study Hours'])
cv_marks = coefficient_of_variation(data['Marks'])
# Print Results
# -----------------------------
print("📌 Coefficient of Variation:")
print(f"Study Hours: {cv_hours:.4f}, Marks: {cv_marks:.4f}\n")

# -----------------------------
# Moments
# -----------------------------
mean_marks = np.mean(marks)
var_marks = np.var(marks, ddof=1)
third_moment = moment(marks, moment=3)
fourth_moment = moment(marks, moment=4)
print("📌 Moments of Marks:")
print(f"Mean: {mean_marks:.2f}, Variance: {var_marks:.2f}, "
      f"3rd Moment: {third_moment:.2f}, 4th Moment: {fourth_moment:.2f}\n")

# -----------------------------
# Skewness and Kurtosis
# -----------------------------
skew_marks = skew(marks)
kurt_marks = kurtosis(marks)


print("📌 Skewness and Kurtosis of Marks:")
print(f"Skewness: {skew_marks:.4f}, Kurtosis (excess): {kurt_marks:.4f}\n")

# -----------------------------
# Correlation
# -----------------------------
pearson_corr, _ = pearsonr(study_hours, marks)
spearman_corr, _ = spearmanr(study_hours, marks)
print("📌 Correlation:")
print(f"Pearson: {pearson_corr:.4f}, Spearman: {spearman_corr:.4f}\n")

# -----------------------------
# Regression (Predict Marks from Study Hours)
# -----------------------------
X = study_hours.reshape(-1, 1)
reg = LinearRegression()
reg.fit(X, marks)

slope = reg.coef_[0]
intercept = reg.intercept_
r_squared = reg.score(X, marks)

print("Regression (Predict Marks from Study Hours):")
print(f"Equation: Marks = {slope:.2f} * StudyHours + {intercept:.2f}")
print(f"R-squared: {r_squared:.4f}\n")

# Visualization of Regression
# -----------------------------
plt.scatter(study_hours, marks, color='blue', label='Actual Data')
plt.plot(study_hours, reg.predict(X), color='red', label='Regression Line')
plt.xlabel("Study Hours")
plt.ylabel("Marks")
plt.title("Study Hours vs Marks - Regression")
plt.legend()
plt.show()

"""# Interpreation

CV → If CV of marks is smaller than study hours, it means marks are more consistent compared to study hours.

Moments → Show spread and shape of marks distribution.

Skewness → If near zero → marks are symmetric; positive → most students scored below average.

Kurtosis → Shows if marks distribution is flatter or more peaked.

Correlation → Strong positive correlation → more study hours → higher marks.

Regression → Predict exam marks from study hours → first ML model idea.

Interpretation:

Skewness > 0 → More students scored below average.

Skewness < 0 → More students scored above average.

Kurtosis > 0 → Peaked distribution (marks clustered near mean).

Kurtosis < 0 → Flatter distribution.
"""

